### ISSUE TITLE
Hey can we connect open your linkedin ?

### ISSUE THREAD

**Issue by rohitadarsh16** [zied-snoussi/zied-snoussi#4]
Hi these side Deepak thanks for following I am python developer

**Comment by rohitadarsh16** [comment]
DO you want to do projects with me i have lot of projects can work on chrome extension ????

**Comment by zied-snoussi** [comment]
Hi Deepak,

Thank you for reaching out! I appreciate the offer, but currently, I'm committed to another project, and my schedule is quite tight. I'm sorry I won't be available to work on projects with you at this time. If anything changes in the future, I'll be sure to let you know.
